### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by thumphries** [thumphries/hydrant#3]
- [ ] Deal with doctypes
- [ ] Deal with comments
- [ ] Add all the canned HTML elements
- [ ] Implement monadic interface (Writer)
- [ ] `INLINEABLE` / `INLINE` almost everywhere
- [ ] Port across the benchmarks from Ambiata repo
- [ ] Extend benchmarks with `type-of-html`
- [ ] Finalise package tree / structure
    - [ ] `hydrant` vs `hydrant` / `hydrant-markup` vs `hydrant-html` / `hydrant-markup`
    - [ ] Check Hackage squatting policies
- [ ] Haddock on every exported symbol
- [ ] Examples at the top level and in `README.md` 
- [ ] Verify license
